---
name: pi485
version: dev1.5.0.0
slug: hyunjins
description: LG HVAC
url: https://github.com/Hyunjinss/PI485
codenotary: yiijin@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  ew11:
    ip: 192.168.1.6
    port: 8899
  mqtt:
    broker: mqtt://192.168.1.10
    id: mqtt
    pw: mqtt
    discovery_topic: homeassistant
    client_id: pi485_client
schema:
  ew11:
    ip: str
    port: int
  mqtt:
    broker: str
    id: str
    pw: password
    discovery_topic: str
    client_id: str
